{% set name = "repoze.who" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e955adf00c1f0b0c715e828979a237ec4bf7ee70827bd97f5e17bf82760dcb30

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - setuptools
    - webob
    - zope.interface

test:
  imports:
    - repoze
    - repoze.who
    - repoze.who.plugins
    - repoze.who.plugins.tests
    - repoze.who.plugins.tests.fixtures
    - repoze.who.tests
  requires:
    - webob
    - zope.interface
    - nose
    - coverage

about:
  home: http://www.repoze.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: repoze.who is an identification and authentication framework for WSGI.
  doc_url: https://pypi.org/project/repoze.who/
  dev_url: https://github.com/repoze/repoze.who

extra:
  recipe-maintainers:
    - mxr-conda
    - mwilson8
    - rluria14
    - oblute
